connections:
  gcp:
    growwapi:
      project_name: growwapi
      service_account_key_path: /Users/kumarohit/Desktop/keys/groww-mf.json
    gw-stage-management:
      project_name: gw-stage-management
      service_account_key_path: /Users/kumarohit/Desktop/keys/groww-mf.json
    analytics-bgv:
      project_name: analytics-bgv
      service_account_key_path: /Users/kumarohit/Desktop/keys/groww-mf.json